name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Run the build script ...
      run: ./build.sh
    - name: Delete the docker password just to be on the safe side ...
      run: rm -f /home/runner/.docker/config.json
